/*
 * ________________________________________________________________________________________________________
 * Copyright (c) 2021 InvenSense Inc. All rights reserved.
 *
 * This software, related documentation and any modifications thereto (collectively "Software") is subject
 * to InvenSense and its licensors' intellectual property rights under U.S. and international copyright
 * and other intellectual property rights laws.
 *
 * InvenSense and its licensors retain all intellectual property and proprietary rights in and to the Software
 * and any use, reproduction, disclosure or distribution of the Software without an express license agreement
 * from InvenSense is strictly prohibited.
 *
 * EXCEPT AS OTHERWISE PROVIDED IN A LICENSE AGREEMENT BETWEEN THE PARTIES, THE SOFTWARE IS
 * PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
 * EXCEPT AS OTHERWISE PROVIDED IN A LICENSE AGREEMENT BETWEEN THE PARTIES, IN NO EVENT SHALL
 * INVENSENSE BE LIABLE FOR ANY DIRECT, SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, OR ANY
 * DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
 * NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
 * OF THE SOFTWARE.
 *
 * ________________________________________________________________________________________________________
 */

#ifndef __INV_IMU_EDMP_PATCHES_DEFS_H__
#define __INV_IMU_EDMP_PATCHES_DEFS_H__

#ifdef __cplusplus
extern "C" {
#endif

#define EDMP_RAM_FEATURE_PRGM_RAM_BASE	0x48
#define EDMP_INVN_MAGNES_I2CM_OPERATIONS	0x4C
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_CHUNK0	0x50
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_BEFORE_ACCEL_CHUNK1	0x54
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_BEFORE_GYRO_CHUNK1	0x58
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_ACCEL_CHUNK1_MBE_UPD_ACCEL	0x5C
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_ACCEL_CHUNK1_BEFORE_SPHERICAL	0x60
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_ACCEL_CHUNK2	0x64
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_GYRO_CHUNK1_MBE_UPD_GYRO	0x68
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_GYRO_CHUNK1_MBE_SEL_BIAS	0x6C
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_GYRO_CHUNK2_BEFORE_STATIONARY	0x70
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_GYRO_CHUNK2_CHECK_STATIONARY	0x74
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_MBE_ACCEL_PROTECT	0x78
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_SPHERICAL_UPD_GYRO_1	0x7C
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_SPHERICAL_UPD_GYRO_2	0x80
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_SPHERICAL_UPD_ACCEL_CHUNK1	0x84
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_SPHERICAL_UPD_ACCEL_CHUNK2	0x88
#define EDMP_INVN_ALGO_ML_PATCH_POINT_AVG_ENTRY	0x8C
#define EDMP_INVN_ALGO_ML_PATCH_POINT_TIME_FEAT_UPD_ENTRY	0x90
#define EDMP_INVN_ALGO_ML_PATCH_POINT_GET_TIME_FEATURE	0x94
#define EDMP_INVN_ALGO_ML_PATCH_POINT_PREDICT_ENTRY	0x98
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_FIFO_PUSH	0x9C
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_RLS_MAG_ACCURACY_LVL	0xA0
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_RLS_MAG_EQUATION_PART1	0xA4
#define EDMP_INVN_ALGO_MRM_PATCH_POINT_DISPATCH	0xA8
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_RLS_MAG_EQUATION_PART2	0xAC
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_RLS_MAG_EQUATION_PART3	0xB0
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_RLS_MAG_PART4_ACCEPTANCE	0xB4
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_SPHERICAL_MAG_PART1	0xB8
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_SPHERICAL_MAG_BEFORE_LOCK	0xBC
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_SPHERICAL_MAG_BEFORE_CORRECT	0xC0
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_BEFORE_MAG_CHUNK1	0xC4
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_BEFORE_MAG_CHUNK4	0xC8
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_BEFORE_MAG_CHUNK5	0xCC
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_BEFORE_MAG_CHUNK6	0xD0
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_BEFORE_MAG_CHUNK7	0xD4
#define EDMP_INVN_ALGO_GAF_PATCH_POINT_MAG_BIAS_QUAL_DECISION	0xD8
#define EDMP_PATCH_CODE_SRAM	0x1800


#ifdef __cplusplus
}
#endif

#endif // __INV_IMU_EDMP_PATCHES_DEFS_H__
